# -*- coding: utf-8 -*-
"""EjClase121125.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2-PavG_SMP6RqxrrAQ6KIzXur6tbZp_
"""

#Adolfo HErnandez Ramirez
#12-11-2025

#Este es un programa para diseñar un tanque con el menor costo posible usando el
#metodo

from scipy.optimize import linprog
c=[-150,-175]
A_ub=[[7,11],[10,8], [1,0],[0,1]]
b_ub=[77,80,9,6]
x1_bounds=(0,None)
x2_bounds=(0,None)
bounds=[x1_bounds,x2_bounds]
result=linprog(c,A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')